
name : latplan
dependencies:
  - python=3.7
  - pip
  - pip:
      - tensorflow-gpu==1.15.2
      - keras==2.2.5
      - h5py<3.0
      - matplotlib
      - progressbar2
      - keras-adabound==0.9.0          # newer versions use TF2 optimizer_v2 API
      - keras-rectified-adam==0.9.0    # newer versions use TF2 optimizer_v2 API
      - timeout_decorator
      - ansicolors
      - scipy==1.4.1
      - scikit-image
      - imageio
      - pillow
      - protobuf==3.20.3
